/*
 * generated by Xtext 2.37.0
 */
package harrysharma.brainrot.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BrainrotUiModule extends AbstractBrainrotUiModule {

	public BrainrotUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
