/*
 * generated by Xtext 2.37.0
 */
package harrysharma.brainrot.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import harrysharma.brainrot.BrainrotRuntimeModule;
import harrysharma.brainrot.BrainrotStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BrainrotIdeSetup extends BrainrotStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BrainrotRuntimeModule(), new BrainrotIdeModule()));
	}
	
}
