/*
 * generated by Xtext 2.37.0
 */
package harrysharma.brainrot.ui.tests;

import com.google.inject.Injector;
import harrysharma.brainrot.ui.internal.BrainrotActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class BrainrotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BrainrotActivator.getInstance().getInjector("harrysharma.brainrot.Brainrot");
	}

}
