/*
 * generated by Xtext 2.37.0
 */
package harrysharma.brainrot;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BrainrotStandaloneSetup extends BrainrotStandaloneSetupGenerated {

	public static void doSetup() {
		new BrainrotStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
