/*
 * generated by Xtext 2.37.0
 */
package harrysharma.brainrot.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BrainrotAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("harrysharma/brainrot/parser/antlr/internal/InternalBrainrot.tokens");
	}
}
