/*
 * generated by Xtext 2.37.0
 */
package harrysharma.brainrot.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBrainrotScopeProvider extends DelegatingScopeProvider {
}
