/**
 * generated by Xtext 2.37.0
 */
package harrysharma.brainrot.brainrot.impl;

import harrysharma.brainrot.brainrot.BrainrotPackage;
import harrysharma.brainrot.brainrot.Sigma;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sigma</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SigmaImpl extends SkibidiImpl implements Sigma
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SigmaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BrainrotPackage.Literals.SIGMA;
  }

} //SigmaImpl
