/**
 * generated by Xtext 2.37.0
 */
package harrysharma.brainrot.brainrot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Greeting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link harrysharma.brainrot.brainrot.Greeting#getGreeting <em>Greeting</em>}</li>
 *   <li>{@link harrysharma.brainrot.brainrot.Greeting#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see harrysharma.brainrot.brainrot.BrainrotPackage#getGreeting()
 * @model
 * @generated
 */
public interface Greeting extends EObject
{
  /**
   * Returns the value of the '<em><b>Greeting</b></em>' attribute.
   * The literals are from the enumeration {@link harrysharma.brainrot.brainrot.TypeOfGreeting}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Greeting</em>' attribute.
   * @see harrysharma.brainrot.brainrot.TypeOfGreeting
   * @see #setGreeting(TypeOfGreeting)
   * @see harrysharma.brainrot.brainrot.BrainrotPackage#getGreeting_Greeting()
   * @model
   * @generated
   */
  TypeOfGreeting getGreeting();

  /**
   * Sets the value of the '{@link harrysharma.brainrot.brainrot.Greeting#getGreeting <em>Greeting</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Greeting</em>' attribute.
   * @see harrysharma.brainrot.brainrot.TypeOfGreeting
   * @see #getGreeting()
   * @generated
   */
  void setGreeting(TypeOfGreeting value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see harrysharma.brainrot.brainrot.BrainrotPackage#getGreeting_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link harrysharma.brainrot.brainrot.Greeting#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Greeting
