/**
 * generated by Xtext 2.37.0
 */
package harrysharma.brainrot.brainrot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sigma</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see harrysharma.brainrot.brainrot.BrainrotPackage#getSigma()
 * @model
 * @generated
 */
public interface Sigma extends Skibidi
{
} // Sigma
